USE Testing

DROP TABLE IF EXISTS LIST_PRODUCT

CREATE TABLE LIST_PRODUCT (
	PRODUCT_NAME VARCHAR(100)
	,PRODUCT_CATEGORY VARCHAR(100)
	,PRODUCT_QUANTITY INT
	,PRODUCT_REMARKS VARCHAR(100)
)

DROP TABLE IF EXISTS LIST_CUSTOMER

CREATE TABLE LIST_CUSTOMER (
	CUSTOMER_NAME VARCHAR(100)
	,ID_NUM VARCHAR(12)
	,SEX VARCHAR(1)
	,ADDRESS VARCHAR(100)
	,PHONE_NUM NUMERIC
)

DROP TABLE IF EXISTS LIST_SALES

CREATE TABLE LIST_SALES (
	PRODUCT_NAME VARCHAR(100)
	,CUSTOMER_NAME VARCHAR(100)
	,SALES_QUANTITY INT
	,BUY_DATE DATE
	,STORE_LOCATION VARCHAR(100)
)

DROP TABLE IF EXISTS LIST_STORE

CREATE TABLE LIST_STORE (
	STORE_NAME VARCHAR(100)
	,STORE_LOCATION VARCHAR(100)
)